version: '3'

networks:
  rs_web_services:
    driver: bridge

services:

  rs_www:
    image: rs_www:1.0.0
    container_name: rs_www
    build: ./
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
      restart_policy:
        condition: any
    environment:
      PORT: 3000
    ports:
      - "3000:3000"
    networks:
      - rs_web_services
